jira1:
  host: https://sportsdataproject.atlassian.net
  username: apolyuhovich@luxoft.com
  token: c1x3m7DDS73r5yRPeyhkCC8D

jira:
  host: https://majidalfuttaim.atlassian.net
  username: apoliu@softserveinc.com
  token: bCHQp0nd8KQFBrgvQXNEEB85